services:
  frontend:
    image: node:20
    container_name: planner-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install; npm run dev"
