###############################################################################
# GROUP MEMBERSHIP MANAGEMENT (GroupMembershipController)
# Endpoints: /admin/groups/{groupId}/users
# Required role: ROLE_ADMIN
###############################################################################

### Pobieranie członków grupy
GET {{host}}/admin/groups/1/users
Content-Type: application/json

###

### Dodanie użytkownika do grupy jako MEMBER
# Wymagania:
# - Musisz być zalogowany jako admin (użyj auth.http)
# - userId musi istnieć (fixtures: 1=admin, 2=user1)
# - groupId musi istnieć (fixtures: 1=group1, 2=group2, 3=group3)
# - role: "MEMBER" lub "member", "OWNER" lub "owner" (case-insensitive)
# Odpowiedzi:
# - 201 CREATED - sukces
# - 400 USER_ALREADY_IN_GROUP - user już w grupie
# - 404 NOT_FOUND - user lub group nie istnieje
POST {{host}}/admin/groups/1/users
Content-Type: application/json

{
  "userId": 2,
  "role": "MEMBER"
}

###

### Dodanie użytkownika do grupy jako OWNER (uppercase)
# Ten request doda user1 (id=2) do group1 z rolą OWNER
POST {{host}}/admin/groups/1/users
Content-Type: application/json

{
  "userId": 2,
  "role": "OWNER"
}

###

### Dodanie użytkownika do grupy jako OWNER (lowercase)
# Role można podać jako lowercase - system automatycznie konwertuje
POST {{host}}/admin/groups/1/users
Content-Type: application/json

{
  "userId": 2,
  "role": "owner"
}

###

### Test: Próba dodania użytkownika który już jest w grupie
# Ten request powinien zwrócić błąd 400 USER_ALREADY_IN_GROUP
# Ponieważ user1 (id=2) już jest w group2
POST {{host}}/admin/groups/2/users
Content-Type: application/json

{
  "userId": 2,
  "role": "MEMBER"
}

###

### Test: Próba dodania nieistniejącego użytkownika
# Ten request powinien zwrócić błąd 404 NOT_FOUND
POST {{host}}/admin/groups/1/users
Content-Type: application/json

{
  "userId": 999,
  "role": "MEMBER"
}

###

### Zmiana roli użytkownika w grupie na OWNER
# Odpowiedzi:
# - 200 OK - sukces (zwraca GroupMembershipDto)
# - 404 NOT_FOUND - user nie jest członkiem grupy lub grupa nie istnieje
# - 422 CANNOT_REMOVE_LAST_OWNER - próba degradacji ostatniego ownera
PATCH {{host}}/admin/groups/1/users/2/role
Content-Type: application/json

{
  "role": "OWNER"
}

###

### Zmiana roli użytkownika w grupie na MEMBER
PATCH {{host}}/admin/groups/1/users/2/role
Content-Type: application/json

{
  "role": "MEMBER"
}

###

### Usunięcie użytkownika z grupy
# Odpowiedzi:
# - 204 NO CONTENT - sukces
# - 404 NOT_FOUND - user nie jest członkiem grupy lub grupa nie istnieje
# - 422 CANNOT_REMOVE_LAST_OWNER - próba usunięcia ostatniego ownera
DELETE {{host}}/admin/groups/1/users/2
Content-Type: application/json

###

### Test: Próba usunięcia ostatniego ownera z grupy
# Ten request powinien zwrócić błąd 422 CANNOT_REMOVE_LAST_OWNER
DELETE {{host}}/admin/groups/1/users/1
Content-Type: application/json

###

### Test: Próba usunięcia użytkownika który nie jest w grupie
# Ten request powinien zwrócić błąd 404 NOT_FOUND
DELETE {{host}}/admin/groups/1/users/999
Content-Type: application/json

###

### Test: Próba zmiany roli ostatniego ownera na MEMBER
# Ten request powinien zwrócić błąd 422 CANNOT_REMOVE_LAST_OWNER
PATCH {{host}}/admin/groups/1/users/1/role
Content-Type: application/json

{
  "role": "MEMBER"
}

###

### Test: Próba zmiany roli użytkownika który nie jest w grupie
# Ten request powinien zwrócić błąd 404 NOT_FOUND
PATCH {{host}}/admin/groups/1/users/999/role
Content-Type: application/json

{
  "role": "MEMBER"
}
