<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260801160339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE friend_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, requester_id INT NOT NULL, addressee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F284D94ED442CF4 ON friend_request (requester_id)');
        $this->addSql('CREATE INDEX IDX_F284D942261B4C3 ON friend_request (addressee_id)');
        $this->addSql('ALTER TABLE friend_request ADD CONSTRAINT FK_F284D94ED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friend_request ADD CONSTRAINT FK_F284D942261B4C3 FOREIGN KEY (addressee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friend_request ADD CONSTRAINT friend_request_no_self_request CHECK (requester_id <> addressee_id)');
        $this->addSql("CREATE UNIQUE INDEX uniq_friend_request_active_pair ON friend_request (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id)) WHERE status IN ('pending', 'accepted')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE friend_request DROP CONSTRAINT FK_F284D94ED442CF4');
        $this->addSql('ALTER TABLE friend_request DROP CONSTRAINT FK_F284D942261B4C3');
        $this->addSql('DROP TABLE friend_request');
    }
}
